[project]
name = "neobank_datalake"
version = "0.0.1"
description = "Neobank data lake pipelines and helpers for Databricks."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "KUWAR Shaurave", email = "kuwarsaurav21@gmail.com" }]
dependencies = [
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=16.3,<16.4",
    "ipykernel",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/neobank_datalake"]

[tool.ruff]
line-length = 120